sudo: required
dist: trusty

branches:
  except:
    - gh-pages

language: cpp

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz

os: linux

compilter: gcc

branches:
  only: 
    - master

notifications:
  email: rojas.delgado.91@gmail.com 

script:
  - mkdir build
  - cd build
  - cmake .. && make