sudo: required
dist: trusty

branches:
  except:
    - gh-pages

language: cpp

env:
  global:
    - GH_REPO_NAME: dnn_opt
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/jairodelgado/dnn_opt.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz

os: linux

compilter: gcc

branches:
  only: 
    - master

notifications:
  email: rojas.delgado.91@gmail.com 

script:
  - mkdir build
  - cd build
  - cmake .. && make

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x doc-generator.sh
  - ./doc-generator.sh