sudo: required
dist: trusty

language: cpp

os: linux

compilter: gcc

branches:
  only: 
    - master

notifications:
  email: rojas.delgado.91@gmail.com 

script:
  - mkdir build
  - cd build
  - cmake .. && make

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x doc-generator.sh
  - ./doc-generator.sh